apiVersion: v1
kind: Service
metadata:
  name: taskforge-backend
  labels:
    app: taskforge-backend
spec:
  selector:
    app: taskforge-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
